# platform :ios, '10.0'

# require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
# require_relative '../node_modules/react-native/scripts/react_native_pods'
# require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

# target 'RNPointSDKMinimalIntegration' do
#   # Pods for RNPointSDKMinimalIntegration
#   config = use_native_modules!
#   use_react_native!(:path => config["reactNativePath"])
  
#   use_unimodules!

#   # permissions_path = '../node_modules/react-native-permissions/ios'

#   # pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways/Permission-LocationAlways.podspec"
#   # pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse/Permission-LocationWhenInUse.podspec"
#   # pod 'Permission-Motion', :path => "#{permissions_path}/Motion/Permission-Motion.podspec"
#   # pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications/Permission-Notifications.podspec"

#   # pod 'RNPermissions', :path => '../node_modules/react-native-permissions'

#   # pod 'RNCPushNotificationIOS', :path => '../node_modules/@react-native-community/push-notification-ios'

#   # pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'

# end


require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'RNPointSDKMinimalIntegration' do
  config = use_native_modules! use_unimodules!
  use_react_native!(:path => config["reactNativePath"])

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end